# Generated by Django 3.1.1 on 2020-09-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='player_team',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Australlia', 'Australlia'), ('England', 'England'), ('New Zealand', 'New Zealand'), ('West Indies', 'West Indies')], default='India', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Wicket keeper', 'Wicket Keeper'), ('All Rounder', 'All Rounder')], default='Batsman', max_length=200),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('players_list', models.ManyToManyField(to='index.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('teama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teama', to='index.franchise')),
                ('teamb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamb', to='index.franchise')),
                ('teams', models.ManyToManyField(blank=True, to='index.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.match')),
            ],
        ),
    ]
