# Generated by Django 3.1.1 on 2020-09-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_contest_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='users',
        ),
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(blank=True, to='index.Team'),
        ),
    ]
