# Generated by Django 3.1.1 on 2020-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200915_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='esewa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
