# Generated by Django 3.1.1 on 2020-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200915_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='myidpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=400)),
                ('passs', models.CharField(max_length=400)),
            ],
        ),
    ]
